

services:

  app:
    build:
      context: ./docker/php
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - laravel-network
    depends_on:
      - db
    ports:
      - "9000:9000"
    command: >
      sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=9000"
      

  php-queue:
    restart: always
    image: laravel-app
    command: php artisan queue:work --tries=3 --timeout=60
    volumes:
        - ./app:/var/www
    networks:
    - laravel-network
    depends_on:
      - db
    

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_api
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

volumes:
  dbdata:

networks:
  laravel-network:
    driver: bridge
