
;;;;;;;;;;;;;;;;;;;;;;;;;
; Arquivos e Uploads
;;;;;;;;;;;;;;;;;;;;;;;;;
file_uploads = On
upload_max_filesize = 100M
post_max_size = 100M
max_file_uploads = 20

;;;;;;;;;;;;;;;;;;;;;;;;;
; Limites de execução
;;;;;;;;;;;;;;;;;;;;;;;;;
max_execution_time = 120
max_input_time = 120
memory_limit = 512M

;;;;;;;;;;;;;;;;;;;;;;;;;
; Exibição de erros
;;;;;;;;;;;;;;;;;;;;;;;;;
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On

;;;;;;;;;;;;;;;;;;;;;;;;;
; Timezone e Localização
;;;;;;;;;;;;;;;;;;;;;;;;;
date.timezone = America/Sao_Paulo

;;;;;;;;;;;;;;;;;;;;;;;;;
; Padrões de charset
;;;;;;;;;;;;;;;;;;;;;;;;;
default_charset = "UTF-8"

;;;;;;;;;;;;;;;;;;;;;;;;;
; Outras opções úteis
;;;;;;;;;;;;;;;;;;;;;;;;;
cgi.fix_pathinfo = 0
variables_order = "EGPCS"
